// Code generated by MockGen. DO NOT EDIT.
// Source: news.go
//
// Generated by this command:
//
//	mockgen -source=news.go -destination=mocks/news_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	model "sportNews/internal/model"

	gomock "go.uber.org/mock/gomock"
)

// MockNewsRepository is a mock of NewsRepository interface.
type MockNewsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNewsRepositoryMockRecorder
	isgomock struct{}
}

// MockNewsRepositoryMockRecorder is the mock recorder for MockNewsRepository.
type MockNewsRepositoryMockRecorder struct {
	mock *MockNewsRepository
}

// NewMockNewsRepository creates a new mock instance.
func NewMockNewsRepository(ctrl *gomock.Controller) *MockNewsRepository {
	mock := &MockNewsRepository{ctrl: ctrl}
	mock.recorder = &MockNewsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNewsRepository) EXPECT() *MockNewsRepositoryMockRecorder {
	return m.recorder
}

// FindNews mocks base method.
func (m *MockNewsRepository) FindNews(id int) (model.News, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNews", id)
	ret0, _ := ret[0].(model.News)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNews indicates an expected call of FindNews.
func (mr *MockNewsRepositoryMockRecorder) FindNews(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNews", reflect.TypeOf((*MockNewsRepository)(nil).FindNews), id)
}

// QueryNewsByPage mocks base method.
func (m *MockNewsRepository) QueryNewsByPage(limit, start int) ([]model.News, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryNewsByPage", limit, start)
	ret0, _ := ret[0].([]model.News)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryNewsByPage indicates an expected call of QueryNewsByPage.
func (mr *MockNewsRepositoryMockRecorder) QueryNewsByPage(limit, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryNewsByPage", reflect.TypeOf((*MockNewsRepository)(nil).QueryNewsByPage), limit, start)
}

// QueryNewsCount mocks base method.
func (m *MockNewsRepository) QueryNewsCount() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryNewsCount")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryNewsCount indicates an expected call of QueryNewsCount.
func (mr *MockNewsRepositoryMockRecorder) QueryNewsCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryNewsCount", reflect.TypeOf((*MockNewsRepository)(nil).QueryNewsCount))
}
