// Code generated by MockGen. DO NOT EDIT.
// Source: rank.go
//
// Generated by this command:
//
//	mockgen -source=rank.go -destination=mocks/rank_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	enum "sportNews/internal/enum"
	model "sportNews/internal/model"

	gomock "go.uber.org/mock/gomock"
)

// MockRankRepository is a mock of RankRepository interface.
type MockRankRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRankRepositoryMockRecorder
	isgomock struct{}
}

// MockRankRepositoryMockRecorder is the mock recorder for MockRankRepository.
type MockRankRepositoryMockRecorder struct {
	mock *MockRankRepository
}

// NewMockRankRepository creates a new mock instance.
func NewMockRankRepository(ctrl *gomock.Controller) *MockRankRepository {
	mock := &MockRankRepository{ctrl: ctrl}
	mock.recorder = &MockRankRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankRepository) EXPECT() *MockRankRepositoryMockRecorder {
	return m.recorder
}

// GetRankDate mocks base method.
func (m *MockRankRepository) GetRankDate(t enum.RankType) (model.SportRank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRankDate", t)
	ret0, _ := ret[0].(model.SportRank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRankDate indicates an expected call of GetRankDate.
func (mr *MockRankRepositoryMockRecorder) GetRankDate(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRankDate", reflect.TypeOf((*MockRankRepository)(nil).GetRankDate), t)
}
